# Generated by Django 5.2.11 on 2026-03-03 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_productmaincategory_productsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubcategory',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='ecomapp.productmaincategory'),
        ),
    ]
